# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
# Production config file for phasik.tv site templating
---
# Site settings
index:
  # CORS domains to request from twitch.tv embed API
  # Allows for embedded iframes to work on these domains
  cors_domains:
    - phasik.com
    - www.phasik.com
    - phasik.tv
    - www.phasik.tv
    - phasiktv.tv
    - www.phasiktv.tv
    - watch.phasik.tv
