# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
# Development config file for phasik.tv site templating
---
# Site settings
index:
  # CORS domains to request from twitch.tv embed API
  # Allows for embedded iframes to work on these domains
  cors_domains:
    - phasik.com
    - www.phasik.com
    - phasik.tv
    - www.phasik.tv
    - watch.phasik.tv
    - 127.0.0.1
    - localhost
