name: docker-phasik-tv
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: lyraphase/docker-phasik.tv
  name: docker-phasik-tv
domains:
  - domain: "watch.phasik.tv"
    type: "PRIMARY"
    wildcard: true
    minimum_tls_version: "1.3"
    zone: "phasik.tv"
